markdown: redcarpet
name: Agile City Performance Playbook
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

baseurl: /SmallCityPerformancePlaybook

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: Jonathan Pichot, Adrian Dahlin, Chris Streich, Maisha Lopa, and Danny Fay
  url: https://github.com/cusp2017

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Who Is This For?
  internal: true
- text: 1. Where To Start
  url: 1-where-to-start/
  internal: true
- text: 2. Data Quality
  url: 2-data-quality/
  internal: true
- text: 3. Public Outreach
  url: 3-public-outreach/
  internal: true
- text: 4. Privacy
  url: 4-privacy/
  internal: true
- text: 5. The Dangers of Data
  url: 5-the-danger-of-data/
  internal: true

repos:
- name: Guides Template
  description: Main repository
  url: https://github.com/18F/guides-template

google_analytics_ua: null

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
